name: xmlstream
version: 0.3.0
author: Joris Hermans <hermansj@gmail.com>
description: A lightweight XML Parser.
homepage: https://github.com/jorishermans/xmlstream
dependencies:
  unittest: '>=0.9.0 <0.9.1'
